# SUMMER ANALYTICS 2023

## WEEK-4 ASSIGNMENT

# New Section

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
from sklearn.preprocessing import LabelEncoder
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

**Let's explore the dataset shall we?**

In [ ]:
# Read the csv file as data
df = pd.read_csv("Train_Data.csv")
df_test = pd.read_csv("Test_Data.csv")
# you may print first few rows
df_test.head()


index pc      ld     m0    m1     m2       m3        m4       m5        m6  \
0      0  E  156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552  168.5460   
1      1  y   58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688  190.6275   
2      2  w  139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544  168.3255   
3      3  z  194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080  196.6545   
4      4  x  173.14   42.0   8.0  136.5  14.9496  103.8765  13.8936  168.3570   

        m7        m8       m9       m10      m11       m12      m13       m14  \
0   8.5896  187.6560   8.3472  178.5945  14.3192  138.0435  12.7008  166.1100   
1  10.1712  202.5870   8.5416  166.9815  15.5944  142.5690  11.6832  177.7230   
2  10.2504  214.2735  11.3392  155.1795  16.0256  132.1005  13.0104  185.6085   
3  10.6304  213.4650   9.9224  191.1000  14.8256  128.0475  12.1984  180.2745   
4   9.6184  191.2050   9.9400  185.0310  13.8664  124.7610      NaN  157.6470   

    ma  
0  m76  
1  m78  
2  m78  
3  m75  
4  m55

In [ ]:
df_test.drop(['index'], inplace=True, axis=1)

In [ ]:
df_test.head()

index pc      ld     m0    m1     m2       m3        m4       m5        m6  \
0      0  E  156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552  168.5460   
1      1  y   58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688  190.6275   
2      2  w  139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544  168.3255   
3      3  z  194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080  196.6545   
4      4  x  173.14   42.0   8.0  136.5  14.9496  103.8765  13.8936  168.3570   

        m7        m8       m9       m10      m11       m12      m13       m14  \
0   8.5896  187.6560   8.3472  178.5945  14.3192  138.0435  12.7008  166.1100   
1  10.1712  202.5870   8.5416  166.9815  15.5944  142.5690  11.6832  177.7230   
2  10.2504  214.2735  11.3392  155.1795  16.0256  132.1005  13.0104  185.6085   
3  10.6304  213.4650   9.9224  191.1000  14.8256  128.0475  12.1984  180.2745   
4   9.6184  191.2050   9.9400  185.0310  13.8664  124.7610      NaN  157.6470   

    ma  
0  m76  
1  m78  
2  m78  
3  m75  
4  m55

In [ ]:
df_test.shape

(3986, 18)

In [ ]:
df.pred.value_counts()

0    17711
1     4873
Name: pred, dtype: int64

In [ ]:
# # sns.rugplot(data=df, x="ma", y="pred")
# plt.figure(figsize=(15,10))
# sns.heatmap(df.corr(), cmap="YlGnBu", annot=True)

In [ ]:
# df.corr().pred

In [ ]:
# df2 = df*df.corr().pred
# df2.head()

In [ ]:
# df.isna().sum()

**Declare feature vector and target variable**

In [ ]:
X= df.drop(["pred", "ma"], axis=1)
y = df.pred
X.head()

Xt = df_test.drop(["index", "ma"], axis=1)
Xt.head()

pc      ld     m0    m1     m2       m3        m4       m5        m6  \
0  E  156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552  168.5460   
1  y   58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688  190.6275   
2  w  139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544  168.3255   
3  z  194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080  196.6545   
4  x  173.14   42.0   8.0  136.5  14.9496  103.8765  13.8936  168.3570   

        m7        m8       m9       m10      m11       m12      m13       m14  
0   8.5896  187.6560   8.3472  178.5945  14.3192  138.0435  12.7008  166.1100  
1  10.1712  202.5870   8.5416  166.9815  15.5944  142.5690  11.6832  177.7230  
2  10.2504  214.2735  11.3392  155.1795  16.0256  132.1005  13.0104  185.6085  
3  10.6304  213.4650   9.9224  191.1000  14.8256  128.0475  12.1984  180.2745  
4   9.6184  191.2050   9.9400  185.0310  13.8664  124.7610      NaN  157.6470

Transforming labels and Scaling

In [ ]:
pc_vals = X.pc.value_counts().sort_values(ascending=False).index
# list_top_10=dataset.X1.value_counts().sort_values(ascending=False).head(10).index
pc_vals

Index(['y', 'E', 'x', 'z', 'w'], dtype='object')

In [ ]:
for category in pc_vals:
    X[category]=np.where(X['pc']==category,1,0)
    Xt[category]=np.where(Xt['pc']==category,1,0)
X.head()
X = X.drop(["pc"], axis=1)
Xt = Xt.drop(["pc"], axis=1)

In [ ]:
# X = X.apply(LabelEncoder().fit_transform)
# Xt = Xt.apply(LabelEncoder().fit_transform)
# Xt.head()

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))
cols=X.columns
cols2=Xt.columns
X[cols] = scaler.fit_transform(X[cols])
Xt[cols2] = scaler.fit_transform(Xt[cols2])
X.head()

ld        m0        m1        m2        m3        m4        m5  \
0  0.143323  0.222222  0.310345  0.208333  0.472846  0.525248  0.316071   
1  0.214857  0.111111  0.551724  0.333333  0.350153  0.502832  0.475383   
2  0.386986  0.000000  0.241379  0.291667  0.559819  0.503893  0.492336   
3  0.253076  0.111111  0.310345  0.250000  0.637498  0.401958  0.302485   
4  0.261610  0.333333  0.310345  0.166667  0.538308  0.576923  0.628774   

         m6        m7        m8  ...       m10       m11       m12       m13  \
0  0.596964  0.432425  0.459139  ...  0.307211  0.576114  0.732314  0.399222   
1  0.535002  0.415649  0.526193  ...  0.401963  0.310522  0.356434  0.401506   
2  0.441889  0.437123  0.338533  ...  0.416570       NaN  0.520407  0.317348   
3  0.575555  0.729164  0.377416  ...  0.556303       NaN  0.537692  0.542417   
4  0.585863  0.492283  0.480908  ...  0.533890  0.420123  0.502721       NaN   

        m14    y    E    x    z    w  
0  0.558231  1.0  0.0  0.0  0.0  0.0  
1  0.256401  1.0  0.0  0.0  0.0  0.0  
2  0.584973  0.0  1.0  0.0  0.0  0.0  
3  0.523057  0.0  0.0  1.0  0.0  0.0  
4  0.391780  0.0  1.0  0.0  0.0  0.0  

[5 rows x 21 columns]

In [ ]:
X = X.fillna(X.median())
Xt = Xt.fillna(X.median())
# X.isna().sum()

In [ ]:
# # X = X.apply(LabelEncoder().fit_transform)
# label_encoder = LabelEncoder()
# X["pc"] = label_encoder.fit_transform(X["pc"])
# X.head()

In [ ]:
# X["ma"] = label_encoder.fit_transform(X["ma"])

In [ ]:
# columns = X.columns
# columns

In [ ]:
# from sklearn.preprocessing import MinMaxScaler
# mms = MinMaxScaler(feature_range=(0, 1))

# X[columns] = mms.fit_transform(X[columns])



In [ ]:
# from sklearn.preprocessing import QuantileTransformer
# scaler = QuantileTransformer()
# X[columns] = scaler.fit_transform(X[columns])

In [ ]:
# X.isna().sum()
# X = X.fillna(X.mean())

**Split data into separate training and test set**

In [ ]:
t=X.join(y)
# plt.figure(figsize=(15,10))
# sns.heatmap(t.corr(), cmap="YlGnBu", annot=True)
# t.head()
factor = t.corr().pred
factor2 =  factor.drop('pred')

df2 = t*factor
df3 = Xt*factor2

X= df2.drop(["pred"], axis=1)
y =df2.pred

Xt = df3
X.head()

ld        m0        m1        m2        m3        m4        m5  \
0  1.630732  0.004254 -0.001147  0.019343  0.000068 -0.020549  0.004604   
1  2.122231  0.002127 -0.002040  0.030949  0.000064 -0.020236  0.005011   
2  3.304907  0.000000 -0.000892  0.027080  0.000070 -0.020251  0.005054   
3  2.384832  0.002127 -0.001147  0.023212  0.000072 -0.018826  0.004570   
4  2.443469  0.006380 -0.001147  0.015475  0.000070 -0.021271  0.005402   

         m6        m7        m8  ...       m10       m11       m12       m13  \
0  0.077208  0.002647  0.061695  ... -0.001668 -0.000891  0.007194  0.000255   
1  0.074860  0.002618  0.063549  ... -0.001820 -0.000738  0.004834  0.000256   
2  0.071331  0.002656  0.058359  ... -0.001843 -0.000851  0.005864  0.000239   
3  0.076396  0.003170  0.059434  ... -0.002066 -0.000851  0.005972  0.000283   
4  0.076787  0.002753  0.062297  ... -0.002031 -0.000801  0.005753  0.000255   

        m14         y         E         x    z    w  
0  0.012835 -0.000023 -0.000000 -0.000000  0.0  0.0  
1  0.009742 -0.000023 -0.000000 -0.000000  0.0  0.0  
2  0.013109 -0.000000 -0.000029 -0.000000  0.0  0.0  
3  0.012474 -0.000000 -0.000000 -0.000063  0.0  0.0  
4  0.011129 -0.000000 -0.000029 -0.000000  0.0  0.0  

[5 rows x 21 columns]

In [ ]:
Xt.head()

ld        m0        m1        m2        m3        m4        m5  \
0  3.047956  0.004962 -0.001402  0.038686  0.000064 -0.017833  0.005170   
1  1.146831  0.005671 -0.002040  0.015475  0.000070 -0.019899  0.005064   
2  2.721069  0.008507 -0.000510  0.027080  0.000069 -0.016883  0.005133   
3  3.780432  0.003545 -0.001020  0.038686  0.000070 -0.021771  0.005004   
4  3.372895  0.002836 -0.001275  0.050292  0.000072 -0.016316  0.005147   

         m6        m7        m8  ...       m10       m11       m12       m13  \
0  0.068910  0.002540  0.057544  ... -0.002100 -0.000793  0.006606  0.000260   
1  0.077938  0.003008  0.062123  ... -0.001963 -0.000863  0.006823  0.000239   
2  0.068819  0.003031  0.065707  ... -0.001825 -0.000887  0.006322  0.000266   
3  0.080402  0.003144  0.065459  ... -0.002247 -0.000821  0.006128  0.000249   
4  0.068832  0.002844  0.058633  ... -0.002175 -0.000768  0.005970  0.000255   

        m14         y         E         x         z         w  
0  0.012315 -0.000000 -0.000029 -0.000000  0.000000  0.000000  
1  0.013176 -0.000023 -0.000000 -0.000000  0.000000  0.000000  
2  0.013760 -0.000000 -0.000000 -0.000000  0.000000  0.000365  
3  0.013365 -0.000000 -0.000000 -0.000000  0.000002  0.000000  
4  0.011687 -0.000000 -0.000000 -0.000063  0.000000  0.000000  

[5 rows x 21 columns]

In [ ]:
# X= df2.drop(["pred", "m1", "m3", "m4", "m9", "m10", "m11", "m13"], axis=1)
# y =df2.pred

# Xt = df3.drop(["m1", "m3", "m4", "m9", "m10", "m11", "m13"], axis=1)
# X.head()

In [ ]:
# Xt.head()

In [ ]:
from imblearn.over_sampling import SMOTE

# Assuming you have your features (X) and target variable (y)

# Instantiate the SMOTE oversampling technique
smote = SMOTE()

# Apply SMOTE to the dataset
X, y = smote.fit_resample(X, y)
X.head()

ld    m0    m1    m2       m3        m4       m5        m6       m7  \
0   83.71  63.0   7.2  52.5  14.0232  130.8300  12.4280  188.8425   8.9520   
1  108.94  31.5  12.8  84.0  13.2840  128.8350  13.5256  183.0990   8.8520   
2  169.65   0.0   5.6  73.5  14.5472  128.9295  13.6424  174.4680   8.9800   
3  122.42  31.5   7.2  63.0  15.0152  119.8575  12.3344  186.8580  10.7208   
4  125.43  94.5   7.2  42.0  14.4176  135.4290  14.5824  187.8135   9.3088   

         m8  ...       m10      m11       m12      m13       m14  y  E  x  z  \
0  201.1905  ...  141.9075  16.0968  150.3390  12.4880  173.1240  1  0  0  0   
1  207.2385  ...  154.7805  13.3304  101.0205  12.5096  131.4075  1  0  0  0   
2  190.3125  ...  156.7650  15.3640  122.5350  11.7136  176.8200  0  1  0  0   
3  193.8195  ...  175.7490  15.3640  124.8030  13.8424  168.2625  0  0  1  0   
4  203.1540  ...  172.7040  14.4720  120.2145  12.5040  150.1185  0  1  0  0   

   w  
0  0  
1  0  
2  0  
3  0  
4  0  

[5 rows x 21 columns]

In [ ]:
X.shape

(35422, 16)

In [ ]:
#  split X and y into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [ ]:
# check the shape of X_train and X_test
print(f"X_train: {X_train.shape}")
print(f"X_test: {X_test.shape}")

X_train: (23732, 21)
X_test: (11690, 21)


Feature Engineering

Feature Engineering is the process of transforming raw data into useful features that help us to understand our model better and increase its predictive power. I will carry out feature engineering on different types of variables.

In [ ]:
# check data types in X_train
X_train.dtypes


pc     float64
ld     float64
m0     float64
m2     float64
m3     float64
m5     float64
m6     float64
m7     float64
m8     float64
m12    float64
m14    float64
ma     float64
dtype: object

Encode categorical variables
Now, I will encode the categorical variables.

In [ ]:
y_train.value_counts()

1.0    11890
0.0    11842
Name: pred, dtype: int64

We can see that all the variables are ordinal categorical data type.



Now let's perform Machine Learning Classification. We'll be predicting the genre based on the given features.

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier, XGBRFClassifier
from xgboost import plot_tree, plot_importance
from sklearn.ensemble import AdaBoostClassifier

from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, roc_curve
from sklearn import preprocessing
from sklearn.feature_selection import RFE
from sklearn.metrics import f1_score

Creating a Predefined function to assess the accuracy of a model. This will be the scoring function

In [ ]:
def score(model, title = "Default"):
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    prediction = pd.DataFrame(preds)
    print(confusion_matrix(y_test, preds))
    accuracy = round(accuracy_score(y_test, preds), 5)
    f1score = f1_score(y_test, preds)
    print('Accuracy for', title, ':', accuracy, '\n', 'f1 score: ', f1score, '\n', prediction.value_counts(), '\n')

 Let's see how a basic Logistic Regressor works on this!

In [ ]:
lg = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial')
score(lg, "Logistic Regression")


[[4436 1433]
 [2135 3686]]
Accuracy for Logistic Regression : 0.69478 
 f1 score:  0.6738574040219378 
 0    6571
1    5119
dtype: int64 



**Now it's your turn. Train the following:**

4. **AdaBoostClassifier** with n_estimators=1000 & random_state=0
5. **RandomForestClassifier** with n_estimators=1000, max_depth=10, random_state=0

**IMPORTANT**: Use the default values for other hyper parameters apart from these. Do **NOT** change these values

In [ ]:
# AdaBoostClassifier
#YOUR CODE HERE
abc = AdaBoostClassifier(n_estimators = 100, random_state=0)
score(abc, title = "AdaBoost Classifier")

[[5407  462]
 [2311 3510]]
Accuracy for AdaBoost Classifier : 0.76279 
 f1 score:  0.7168385581537833 0    7718
1    3972
dtype: int64 



AdaBoost performs poorly, but Random Forest looks great!

Now look at the import statements. There may be a few models you may or may not have seen. Use those models to beat the score you achieved in the cell above! Play around with their hyper parameters.
We suggest going through their documentations before using them.

In [ ]:
# Naive Bayes: GaussianNB
#YOUR CODE HERE
nbc = GaussianNB()
score(nbc, "Naive Bayes")

# KNN: KNeighborsClassifier
#YOUR CODE HERE
knb = KNeighborsClassifier(n_neighbors=10)
score(knb, "K Neighbors")

# Decission trees: DecisionTreeClassifier
#YOUR CODE HERE
dst = DecisionTreeClassifier(max_depth=15 ,random_state=0)
score(dst, "Decision trees")

[[5215  654]
 [2256 3565]]
Accuracy for Naive Bayes : 0.75107 
 f1 score:  0.7101593625498007 
 0    7471
1    4219
dtype: int64 

[[3382 2487]
 [1156 4665]]
Accuracy for K Neighbors : 0.68837 
 f1 score:  0.7191860016958299 
 1    7152
0    4538
dtype: int64 

[[4523 1346]
 [1696 4125]]
Accuracy for Decision trees : 0.73978 
 f1 score:  0.7306057385759831 
 0    6219
1    5471
dtype: int64 



In [ ]:
# build the lightgbm model
import lightgbm as lgb
ltgm = lgb.LGBMClassifier(n_estimators= 100, learning_rate=0.1)
score(ltgm, "Light GBM")

[[5822   47]
 [1708 4113]]
Accuracy for Light GBM : 0.84987 
 f1 score:  0.8241659152389541 
 0    7530
1    4160
dtype: int64 



Visualize decision-trees

Decision Tree Classifier with criterion gini index,max_depth=10, random_state=0

In [ ]:
#YOUR CODE HERE
dst2 = DecisionTreeClassifier(criterion="gini", max_depth=15, random_state=0)
score(dst2, "Decision trees")


[[3922 1947]
 [1548 4273]]
Accuracy for Decision trees : 0.70103 
 f1 score:  0.7097417158043352 1    6220
0    5470
dtype: int64 



Decision Tree Classifier with criterion entripy index,max_depth=8, random_state=0

In [ ]:
#YOUR CODE HERE
dst3 = DecisionTreeClassifier(criterion= "log_loss", max_depth=17,random_state=10 )
score(dst3, "Decision trees")


[[4441 1428]
 [1628 4193]]
Accuracy for Decision trees : 0.73858 
 f1 score:  0.7329138262541514 
 0    6069
1    5621
dtype: int64 



Use XGBClassifier with n_estimators=1000 and learning_rate=0.01

In [ ]:
# XGBClassifier
#YOUR CODE HERE
# y_train = y_train.apply(LabelEncoder().fit_transform)
# y_train = LabelEncoder().fit_transform(y_train)
# y_test = y_test.apply(LabelEncoder().fit_transform)
# y_test = LabelEncoder().fit_transform(y_test)
xgbst = XGBClassifier(n_estimators=100, learning_rate=0.1, reg_alpha=0.005)
score(xgbst, "XGBoost Classifier")

[[5797   72]
 [1725 4096]]
Accuracy for XGBoost Classifier : 0.84628 
 f1 score:  0.8201021123235559 
 0    7522
1    4168
dtype: int64 



In [ ]:
# XGBClassifier
#YOUR CODE HERE
# y_train = y_train.apply(LabelEncoder().fit_transform)
# y_train = LabelEncoder().fit_transform(y_train)
# y_test = y_test.apply(LabelEncoder().fit_transform)
# y_test = LabelEncoder().fit_transform(y_test)
xgbst = XGBClassifier(n_estimators=100, learning_rate=0.1)
score(xgbst, "XGBoost Classifier")

[[5799   70]
 [1667 4154]]
Accuracy for XGBoost Classifier : 0.85141 
 f1 score:  0.8270781483325037 0    7466
1    4224
dtype: int64 



In [ ]:
# # Cell to find Feature Importance
# #YOUR CODE HERE
# # print()
# xgbst2.feature_importances_

In [ ]:
# #YOUR CODE HERE
# from sklearn.metrics import classification_report
# print(classification_report(y_test, y_pred))


In [ ]:
# build the lightgbm model

# score(ltgm, "Light GBM")



In [ ]:
model = DecisionTreeClassifier(max_depth=25 ,random_state=20)
score(model, "Decision trees")

[[4262 1607]
 [1338 4483]]
Accuracy for Decision trees : 0.74808 
 f1 score:  0.752749559230963 
 1    6090
0    5600
dtype: int64 



In [ ]:
model=ltgm
model.fit(X_train, y_train)
preds = model.predict(Xt)


In [ ]:
prediction = pd.DataFrame(preds, columns=['pred'])

In [ ]:
prediction.value_counts()
# prediction


pred
0.0     3986
dtype: int64

In [ ]:
prediction

pred
0      0.0
1      1.0
2      0.0
3      0.0
4      1.0
...    ...
3981   0.0
3982   0.0
3983   0.0
3984   0.0
3985   0.0

[3986 rows x 1 columns]

model = DecisionTreeClassifier(max_depth=15 ,random_state=0)
output for this

In [ ]:
# Specify the file path and name for the CSV file
csv_file_path = "output.csv"

# Export the DataFrame to a CSV file
prediction.to_csv(csv_file_path, index=False)

In [ ]:
model =  AdaBoostClassifier(n_estimators = 500, random_state=0)
# score(model)
# model=ltgm
model.fit(X_train, y_train)
preds = model.predict(Xt)

prediction = pd.DataFrame(preds, columns=['pred'])
prediction.value_counts()

pred
0       3875
1        111
dtype: int64

In [ ]:
# xgbst = XGBClassifier(n_estimators=100, learning_rate=0.1, reg_alpha=0.1, reg_lambda = 0.1)
# xgbst = XGBClassifier(n_estimators=100, learning_rate=0.1, reg_alpha=0.005)
ltgm = lgb.LGBMClassifier(n_estimators= 500, learning_rate=0.1)
model= ltgm
# model= xgbst
model.fit(X_train, y_train)
preds = model.predict(Xt)

prediction = pd.DataFrame(preds, columns=['pred'])
prediction.value_counts()

pred
0       3860
1        126
dtype: int64

In [ ]:
# dst3 = DecisionTreeClassifier(criterion= "gini", max_depth=30, random_state=0)
dst3 = DecisionTreeClassifier(criterion= "log_loss", max_depth=17,random_state=10 )
model=dst3
model.fit(X_train, y_train)
preds = model.predict(Xt)

prediction = pd.DataFrame(preds, columns=['pred'])
prediction.value_counts()

pred
0       3033
1        953
dtype: int64

In [ ]:
# Specify the file path and name for the CSV file
csv_file_path = "output3.csv"

# Export the DataFrame to a CSV file
prediction.to_csv(csv_file_path, index=False)