# SUMMER ANALYTICS 2023

## WEEK-4 ASSIGNMENT

# New Section

In [503]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
from sklearn.preprocessing import LabelEncoder
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

**Let's explore the dataset shall we?**

In [504]:
# Read the csv file as data
df = pd.read_csv("Train_Data.csv")
df_test = pd.read_csv("Test_Data.csv")
# you may print first few rows
df_test.head()


index pc      ld     m0    m1     m2       m3        m4       m5        m6  \
0      0  E  156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552  168.5460   
1      1  y   58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688  190.6275   
2      2  w  139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544  168.3255   
3      3  z  194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080  196.6545   
4      4  x  173.14   42.0   8.0  136.5  14.9496  103.8765  13.8936  168.3570   

        m7        m8       m9       m10      m11       m12      m13       m14  \
0   8.5896  187.6560   8.3472  178.5945  14.3192  138.0435  12.7008  166.1100   
1  10.1712  202.5870   8.5416  166.9815  15.5944  142.5690  11.6832  177.7230   
2  10.2504  214.2735  11.3392  155.1795  16.0256  132.1005  13.0104  185.6085   
3  10.6304  213.4650   9.9224  191.1000  14.8256  128.0475  12.1984  180.2745   
4   9.6184  191.2050   9.9400  185.0310  13.8664  124.7610      NaN  157.6470   

    ma  
0  m76  
1  m78  
2  m78  
3  m75  
4  m55

In [505]:
df_test.drop(['index'], inplace=True, axis=1)

In [506]:
df_test.head()

pc      ld     m0    m1     m2       m3        m4       m5        m6  \
0  E  156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552  168.5460   
1  y   58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688  190.6275   
2  w  139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544  168.3255   
3  z  194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080  196.6545   
4  x  173.14   42.0   8.0  136.5  14.9496  103.8765  13.8936  168.3570   

        m7        m8       m9       m10      m11       m12      m13       m14  \
0   8.5896  187.6560   8.3472  178.5945  14.3192  138.0435  12.7008  166.1100   
1  10.1712  202.5870   8.5416  166.9815  15.5944  142.5690  11.6832  177.7230   
2  10.2504  214.2735  11.3392  155.1795  16.0256  132.1005  13.0104  185.6085   
3  10.6304  213.4650   9.9224  191.1000  14.8256  128.0475  12.1984  180.2745   
4   9.6184  191.2050   9.9400  185.0310  13.8664  124.7610      NaN  157.6470   

    ma  
0  m76  
1  m78  
2  m78  
3  m75  
4  m55

In [491]:
df_test.shape

(3986, 18)

In [272]:
df.pred.value_counts()

0    17711
1     4873
Name: pred, dtype: int64

In [14]:
# # sns.rugplot(data=df, x="ma", y="pred")
# plt.figure(figsize=(15,10))
# sns.heatmap(df.corr(), cmap="YlGnBu", annot=True)

In [15]:
# df.corr().pred

In [16]:
# df2 = df*df.corr().pred
# df2.head()

**Declare feature vector and target variable**

In [507]:
# X= df.drop(["pred", "pc", "ma"], axis=1)
X= df.drop(["pred"], axis=1)
y = df.pred
X.head()

# Xt = df_test.drop(["pc", "ma"], axis=1)
Xt= df_test
Xt.head()

pc      ld     m0    m1     m2       m3        m4       m5        m6  \
0  E  156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552  168.5460   
1  y   58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688  190.6275   
2  w  139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544  168.3255   
3  z  194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080  196.6545   
4  x  173.14   42.0   8.0  136.5  14.9496  103.8765  13.8936  168.3570   

        m7        m8       m9       m10      m11       m12      m13       m14  \
0   8.5896  187.6560   8.3472  178.5945  14.3192  138.0435  12.7008  166.1100   
1  10.1712  202.5870   8.5416  166.9815  15.5944  142.5690  11.6832  177.7230   
2  10.2504  214.2735  11.3392  155.1795  16.0256  132.1005  13.0104  185.6085   
3  10.6304  213.4650   9.9224  191.1000  14.8256  128.0475  12.1984  180.2745   
4   9.6184  191.2050   9.9400  185.0310  13.8664  124.7610      NaN  157.6470   

    ma  
0  m76  
1  m78  
2  m78  
3  m75  
4  m55

Transforming labels and Scaling

In [508]:
pc_vals = X.pc.value_counts().sort_values(ascending=False).index
ma_vals = X.ma.value_counts().sort_values(ascending=False).index
# list_top_10=dataset.X1.value_counts().sort_values(ascending=False).head(10).index
ma_vals, pc_vals

(Index(['m78', 'm76', 'm55', 'm75'], dtype='object'),
 Index(['y', 'E', 'x', 'z', 'w'], dtype='object'))

In [509]:
for category in pc_vals:
    X[category]=np.where(X['pc']==category,1,0)
    Xt[category]=np.where(Xt['pc']==category,1,0)
X.head()
X = X.drop(["pc"], axis=1)
Xt = Xt.drop(["pc"], axis=1)

for category in ma_vals:
    X[category]=np.where(X['ma']==category,1,0)
    Xt[category]=np.where(Xt['ma']==category,1,0)
X.head()
X = X.drop(["ma"], axis=1)
Xt = Xt.drop(["ma"], axis=1)

In [307]:
# X = X.apply(LabelEncoder().fit_transform)
# Xt = Xt.apply(LabelEncoder().fit_transform)
# Xt.head()

In [510]:
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler(feature_range=(0, 5))
# cols=X.columns
# cols2=Xt.columns
# X[cols] = scaler.fit_transform(X[cols])
# Xt[cols2] = scaler.fit_transform(Xt[cols2])
# X.head()

In [184]:
# # Box-Cox
# from sklearn.preprocessing import RobustScaler
# scaler = RobustScaler()

# cols=X.columns
# cols2=Xt.columns
# X[cols] = scaler.fit_transform(X[cols])
# Xt[cols2] = scaler.fit_transform(Xt[cols2])
# X.head()

In [512]:
X = X.fillna(X.mean())
Xt = Xt.fillna(X.mean())
# X.isna().sum()

In [ ]:
# # X = X.apply(LabelEncoder().fit_transform)
# label_encoder = LabelEncoder()
# X["pc"] = label_encoder.fit_transform(X["pc"])
# X.head()

In [ ]:
# X["ma"] = label_encoder.fit_transform(X["ma"])

In [ ]:
# columns = X.columns
# columns

In [ ]:
# from sklearn.preprocessing import MinMaxScaler
# mms = MinMaxScaler(feature_range=(0, 1))

# X[columns] = mms.fit_transform(X[columns])



In [ ]:
# from sklearn.preprocessing import QuantileTransformer
# scaler = QuantileTransformer()
# X[columns] = scaler.fit_transform(X[columns])

In [ ]:
# X.isna().sum()
# X = X.fillna(X.mean())

**Split data into separate training and test set**

In [396]:
# t=X.join(y)
# # plt.figure(figsize=(15,10))
# # sns.heatmap(t.corr(), cmap="YlGnBu", annot=True)
# # t.head()
# factor = t.corr().pred
# factor2 =  factor.drop('pred')

# df2 = t*factor
# df3 = Xt*factor2

# X= df2.drop(["pred"], axis=1)
# y =df2.pred

# Xt = df3
# X.head()

ld        m0        m1        m2        m3        m4        m5  \
0  10.887514  0.550198 -0.063289  0.970941  0.057361 -1.560821  0.228444   
1  14.168986  0.275099 -0.112514  1.553506  0.054337 -1.537020  0.248619   
2  22.065067  0.000000 -0.049225  1.359318  0.059504 -1.538148  0.250766   
3  15.922225  0.275099 -0.063289  1.165130  0.061418 -1.429917  0.226723   
4  16.313713  0.825297 -0.063289  0.776753  0.058974 -1.615687  0.268045   

         m6        m7        m8  ...       m14         y        E         x  \
0  3.249937  0.138666  3.366646  ...  1.100297 -0.002744 -0.00000 -0.000000   
1  3.151092  0.137117  3.467851  ...  0.835166 -0.002744 -0.00000 -0.000000   
2  3.002555  0.139099  3.184618  ...  1.123787 -0.000000 -0.00294 -0.000000   
3  3.215784  0.166064  3.243303  ...  1.069400 -0.000000 -0.00000 -0.013415   
4  3.232228  0.144192  3.399503  ...  0.954085 -0.000000 -0.00294 -0.000000   

     z    w       m78      m76       m55  m75  
0  0.0  0.0  0.010819 -0.00000 -0.000000  0.0  
1  0.0  0.0  0.010819 -0.00000 -0.000000  0.0  
2  0.0  0.0  0.000000 -0.00294 -0.000000  0.0  
3  0.0  0.0  0.000000 -0.00000 -0.013415  0.0  
4  0.0  0.0  0.000000 -0.00294 -0.000000  0.0  

[5 rows x 25 columns]

In [119]:
Xt.head()

ld        m0        m1        m2        m3        m4        m5  \
0  0.049092  0.002108 -0.003719  0.008807  0.001352 -0.004442  0.011904   
1  0.007558  0.002409 -0.005409  0.003523  0.002213 -0.006568  0.011110   
2  0.041950  0.003614 -0.001352  0.006165  0.002064 -0.003464  0.011625   
3  0.065094  0.001506 -0.002705  0.008807  0.002289 -0.008495  0.010665   
4  0.056190  0.001205 -0.003381  0.011449  0.002586 -0.002880  0.011733   

         m6        m7        m8        m9       m10       m11       m12  \
0  0.004996  0.005629  0.006049 -0.001262 -0.002959 -0.002216  0.003912   
1  0.010495  0.009930  0.009353 -0.001375 -0.002533 -0.002866  0.004167   
2  0.004942  0.010146  0.011938 -0.002990 -0.002100 -0.003085  0.003577   
3  0.011996  0.011179  0.011760 -0.002172 -0.003417 -0.002474  0.003348   
4  0.004949  0.008427  0.006835 -0.002182 -0.003195 -0.001986  0.003163   

        m13       m14       m78      m76       m55       m75  
0  0.001488  0.002989  0.000000 -0.00294 -0.000000  0.000000  
1  0.001096  0.003605  0.010819 -0.00000 -0.000000  0.000000  
2  0.001608  0.004024  0.010819 -0.00000 -0.000000  0.000000  
3  0.001294  0.003741  0.000000 -0.00000 -0.000000  0.002963  
4  0.001184  0.002540  0.000000 -0.00000 -0.013415  0.000000

In [ ]:
# X= df2.drop(["pred", "m1", "m3", "m4", "m9", "m10", "m11", "m13"], axis=1)
# y =df2.pred

# Xt = df3.drop(["m1", "m3", "m4", "m9", "m10", "m11", "m13"], axis=1)
# X.head()

In [223]:
Xt.head()

ld     m0    m1     m2       m3        m4       m5        m6       m7  \
0  156.46   73.5   8.8  105.0  13.2768  113.5365  13.9552  168.5460   8.5896   
1   58.87   84.0  12.8   42.0  14.4440  126.6930  13.6688  190.6275  10.1712   
2  139.68  126.0   3.2   73.5  14.2432  107.4885  13.8544  168.3255  10.2504   
3  194.06   52.5   6.4  105.0  14.5480  138.6105  13.5080  196.6545  10.6304   
4  173.14   42.0   8.0  136.5  14.9496  103.8765  13.8936  168.3570   9.6184   

         m8  ...       m14  y  E  x  z  w  m78  m76  m55  m75  
0  187.6560  ...  166.1100  0  1  0  0  0    0    1    0    0  
1  202.5870  ...  177.7230  1  0  0  0  0    1    0    0    0  
2  214.2735  ...  185.6085  0  0  0  0  1    1    0    0    0  
3  213.4650  ...  180.2745  0  0  0  1  0    0    0    0    1  
4  191.2050  ...  157.6470  0  0  1  0  0    0    0    1    0  

[5 rows x 25 columns]

In [310]:
# from sklearn.feature_selection import SelectKBest
# from sklearn.feature_selection import chi2
# best_f = SelectKBest(score_func=chi2, k=10)
# fit = best_f.fit(X,y)
# dfscores=pd.DataFrame(fit.scores_)
# dfcols= pd.DataFrame(X.columns)
# featureScores = pd.concat([dfcols, dfscores], axis=1)
# featureScores.columns= ['Specs', 'Score']
# featuresScores

In [238]:
# X= X.drop(["m3", "m5", "m7", "m9", "m10", "m11", "m13"], axis=1)
# Xt= Xt.drop(["m3", "m5", "m7", "m9", "m10", "m11", "m13"], axis=1)
# # y =df2.pred

In [192]:
# X = X[['ld', 'm0', 'm2']].copy()
# Xt = Xt[['ld', 'm0', 'm2']].copy()

In [280]:
X.head()

ld    m0    m1    m2       m3        m4       m5        m6       m7  \
0   83.71  63.0   7.2  52.5  14.0232  130.8300  12.4280  188.8425   8.9520   
1  108.94  31.5  12.8  84.0  13.2840  128.8350  13.5256  183.0990   8.8520   
2  169.65   0.0   5.6  73.5  14.5472  128.9295  13.6424  174.4680   8.9800   
3  122.42  31.5   7.2  63.0  15.0152  119.8575  12.3344  186.8580  10.7208   
4  125.43  94.5   7.2  42.0  14.4176  135.4290  14.5824  187.8135   9.3088   

         m8       m9       m10      m11       m12      m13       m14  
0  201.1905   9.2896  141.9075  16.0968  150.3390  12.4880  173.1240  
1  207.2385   8.4704  154.7805  13.3304  101.0205  12.5096  131.4075  
2  190.3125  11.3056  156.7650  15.3640  122.5350  11.7136  176.8200  
3  193.8195  10.6096  175.7490  15.3640  124.8030  13.8424  168.2625  
4  203.1540   9.8280  172.7040  14.4720  120.2145  12.5040  150.1185

In [513]:
from imblearn.over_sampling import SMOTE

# Assuming you have your features (X) and target variable (y)

# Instantiate the SMOTE oversampling technique
smote = SMOTE()

# Apply SMOTE to the dataset
X, y = smote.fit_resample(X, y)
X.head()

ld    m0    m1    m2       m3        m4       m5        m6       m7  \
0   83.71  63.0   7.2  52.5  14.0232  130.8300  12.4280  188.8425   8.9520   
1  108.94  31.5  12.8  84.0  13.2840  128.8350  13.5256  183.0990   8.8520   
2  169.65   0.0   5.6  73.5  14.5472  128.9295  13.6424  174.4680   8.9800   
3  122.42  31.5   7.2  63.0  15.0152  119.8575  12.3344  186.8580  10.7208   
4  125.43  94.5   7.2  42.0  14.4176  135.4290  14.5824  187.8135   9.3088   

         m8  ...       m14  y  E  x  z  w  m78  m76  m55  m75  
0  201.1905  ...  173.1240  1  0  0  0  0    1    0    0    0  
1  207.2385  ...  131.4075  1  0  0  0  0    1    0    0    0  
2  190.3125  ...  176.8200  0  1  0  0  0    0    1    0    0  
3  193.8195  ...  168.2625  0  0  1  0  0    0    0    1    0  
4  203.1540  ...  150.1185  0  1  0  0  0    0    1    0    0  

[5 rows x 25 columns]

In [311]:
# # Undersampler
# from imblearn.under_sampling import RandomUnderSampler
# undersampler = RandomUnderSampler()

# # Perform undersampling
# X,y = undersampler.fit_resample(X, y)

# # Create a new balanced dataframe
# # balanced_df = pd.DataFrame(X, columns=['feature1', 'feature2'])
# # balanced_df['target'] = y_resampled
# X.head()

In [290]:
X.shape

(9746, 16)

In [514]:
#  split X and y into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 40)

In [515]:
# check the shape of X_train and X_test
print(f"X_train: {X_train.shape}")
print(f"X_test: {X_test.shape}")

X_train: (23732, 25)
X_test: (11690, 25)


Feature Engineering

Feature Engineering is the process of transforming raw data into useful features that help us to understand our model better and increase its predictive power. I will carry out feature engineering on different types of variables.

In [477]:
# check data types in X_train
X_train.dtypes


ld     float64
m0     float64
m1     float64
m2     float64
m3     float64
m4     float64
m5     float64
m6     float64
m7     float64
m8     float64
m9     float64
m10    float64
m11    float64
m12    float64
m13    float64
m14    float64
y      float64
E      float64
x      float64
z      float64
w      float64
m78    float64
m76    float64
m55    float64
m75    float64
dtype: object

Encode categorical variables
Now, I will encode the categorical variables.

In [ ]:
y_train.value_counts()

1.0    11890
0.0    11842
Name: pred, dtype: int64

We can see that all the variables are ordinal categorical data type.



Now let's perform Machine Learning Classification. We'll be predicting the genre based on the given features.

In [478]:
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier, XGBRFClassifier
from xgboost import plot_tree, plot_importance
from sklearn.ensemble import AdaBoostClassifier

from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, roc_curve
from sklearn import preprocessing
from sklearn.feature_selection import RFE
from sklearn.metrics import f1_score

Creating a Predefined function to assess the accuracy of a model. This will be the scoring function

In [479]:
def score(model, title = "Default"):
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    prediction = pd.DataFrame(preds)
    print(confusion_matrix(y_test, preds))
    accuracy = round(accuracy_score(y_test, preds), 5)
    f1score = f1_score(y_test, preds)
    print('Accuracy for', title, ':', accuracy, '\n', 'f1 score: ', f1score, '\n', prediction.value_counts(), '\n')

 Let's see how a basic Logistic Regressor works on this!

In [516]:
lg = LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial')
score(lg, "Logistic Regression")


[[4337 1425]
 [2199 3729]]
Accuracy for Logistic Regression : 0.68999 
 f1 score:  0.6729832160259881 
 0    6536
1    5154
dtype: int64 



Training the Models


In [517]:
# AdaBoostClassifier
#YOUR CODE HERE
abc = AdaBoostClassifier(n_estimators = 100, random_state=0)
score(abc, title = "AdaBoost Classifier")

[[5331  431]
 [2340 3588]]
Accuracy for AdaBoost Classifier : 0.76296 
 f1 score:  0.721423544787373 
 0    7671
1    4019
dtype: int64 



In [459]:
# # Random Forest
# #YOUR CODE HERE
# rfst = RandomForestClassifier(n_estimators = 1000, max_depth=10, random_state=0)
# score(rfst, title = "Random Forest Classifier")

In [518]:
# Naive Bayes: GaussianNB
#YOUR CODE HERE
nbc = GaussianNB()
score(nbc, "Naive Bayes")

# KNN: KNeighborsClassifier
#YOUR CODE HERE
knb = KNeighborsClassifier(n_neighbors=10)
score(knb, "K Neighbors")

# Decission trees: DecisionTreeClassifier
#YOUR CODE HERE
dst = DecisionTreeClassifier(max_depth=15 ,random_state=0)
score(dst, "Decision trees")

[[4530 1232]
 [2065 3863]]
Accuracy for Naive Bayes : 0.71796 
 f1 score:  0.700898122108319 
 0    6595
1    5095
dtype: int64 

[[3303 2459]
 [1124 4804]]
Accuracy for K Neighbors : 0.6935 
 f1 score:  0.7283754074747935 
 1    7263
0    4427
dtype: int64 

[[4632 1130]
 [1815 4113]]
Accuracy for Decision trees : 0.74808 
 f1 score:  0.7363709605227822 
 0    6447
1    5243
dtype: int64 



In [519]:
dst = DecisionTreeClassifier(max_depth=15 ,random_state=0)
score(dst, "Decision trees")



[[4632 1130]
 [1815 4113]]
Accuracy for Decision trees : 0.74808 
 f1 score:  0.7363709605227822 
 0    6447
1    5243
dtype: int64 



In [520]:
# build the lightgbm model
import lightgbm as lgb
# ltgm = lgb.LGBMClassifier(n_estimators= 100, learning_rate=0.1)
lgb.LGBMClassifier(n_estimators= 300, learning_rate=0.9, random_state = 20, reg_alpha=0.01, reg_lambda = 0.5)
score(ltgm, "Light GBM")


[[5354  408]
 [1453 4475]]
Accuracy for Light GBM : 0.8408 
 f1 score:  0.8278605124410323 
 0    6807
1    4883
dtype: int64 



Visualize decision-trees

In [ ]:

# from sklearn import tree
# plt.figure(figsize=(200,30))

# #change the model name
# tree.plot_tree(dst)
# plt.show()

Decision Tree Classifier with criterion gini index,max_depth=10, random_state=0

In [521]:
#YOUR CODE HERE
dst2 = DecisionTreeClassifier(criterion="gini", max_depth=15, random_state=0)
score(dst2, "Decision trees")


[[4632 1130]
 [1815 4113]]
Accuracy for Decision trees : 0.74808 
 f1 score:  0.7363709605227822 
 0    6447
1    5243
dtype: int64 



Decision Tree Classifier with criterion entripy index,max_depth=8, random_state=0

In [522]:
#YOUR CODE HERE
dst3 = DecisionTreeClassifier(criterion= "log_loss", max_depth=15, random_state=10,  min_samples_split = 10)
score(dst3, "Decision trees")


[[4603 1159]
 [1823 4105]]
Accuracy for Decision trees : 0.74491 
 f1 score:  0.7335596854896355 
 0    6426
1    5264
dtype: int64 



Use XGBClassifier with n_estimators=1000 and learning_rate=0.01

In [51]:
# XGBClassifier
#YOUR CODE HERE
# y_train = y_train.apply(LabelEncoder().fit_transform)
# y_train = LabelEncoder().fit_transform(y_train)
# y_test = y_test.apply(LabelEncoder().fit_transform)
# y_test = LabelEncoder().fit_transform(y_test)
xgbst = XGBClassifier(n_estimators=100, learning_rate=0.1, reg_alpha=0.005)
score(xgbst, "XGBoost Classifier")

[[5689   73]
 [1718 4210]]
Accuracy for XGBoost Classifier : 0.84679 
 f1 score:  0.8246009205758495 
 0    7407
1    4283
dtype: int64 



In [297]:
# XGBClassifier
#YOUR CODE HERE
# y_train = y_train.apply(LabelEncoder().fit_transform)
# y_train = LabelEncoder().fit_transform(y_train)
# y_test = y_test.apply(LabelEncoder().fit_transform)
# y_test = LabelEncoder().fit_transform(y_test)
xgbst = XGBClassifier(n_estimators=100, learning_rate=0.1)
score(xgbst, "XGBoost Classifier")

[[893 668]
 [788 868]]
Accuracy for XGBoost Classifier : 0.5474 
 f1 score:  0.5438596491228069 
 0    1681
1    1536
dtype: int64 



Visualize XGBClassifier

Now, heres a task for you. Try XGBRFClassifier on your own.

In [321]:
# XGBRFClassifier
xgbrf = XGBRFClassifier(n_estimators=500, max_depth=10 )
score(xgbrf, "XGBRF Classifier")

[[5571  191]
 [2400 3528]]
Accuracy for XGBRF Classifier : 0.77836 
 f1 score:  0.731419094018866 
 0    7971
1    3719
dtype: int64 



In [ ]:
# # Cell to find Feature Importance
# #YOUR CODE HERE
# # print()
# xgbst2.feature_importances_

In [ ]:
# #YOUR CODE HERE
# from sklearn.metrics import classification_report
# print(classification_report(y_test, y_pred))


In [ ]:
# build the lightgbm model

# score(ltgm, "Light GBM")



In [322]:
model = DecisionTreeClassifier(max_depth=25 ,random_state=20)
score(model, "Decision trees")

[[4219 1543]
 [1401 4527]]
Accuracy for Decision trees : 0.74816 
 f1 score:  0.754625770961827 
 1    6070
0    5620
dtype: int64 



In [ ]:
model=ltgm
model.fit(X_train, y_train)
preds = model.predict(Xt)


In [ ]:
prediction = pd.DataFrame(preds, columns=['pred'])

In [ ]:
prediction.value_counts()
# prediction


pred
0.0     3986
dtype: int64

In [ ]:
prediction

pred
0      0.0
1      1.0
2      0.0
3      0.0
4      1.0
...    ...
3981   0.0
3982   0.0
3983   0.0
3984   0.0
3985   0.0

[3986 rows x 1 columns]

model = DecisionTreeClassifier(max_depth=15 ,random_state=0)
output for this

In [ ]:
# Specify the file path and name for the CSV file
csv_file_path = "output.csv"

# Export the DataFrame to a CSV file
prediction.to_csv(csv_file_path, index=False)

In [523]:
model =  AdaBoostClassifier(n_estimators = 500, random_state=0)
# score(model)
# model=ltgm
model.fit(X_train, y_train)
preds = model.predict(Xt)

prediction = pd.DataFrame(preds, columns=['pred'])
prediction.value_counts()

pred
0       3892
1         94
dtype: int64

In [524]:
# xgbst = XGBClassifier(n_estimators=100, learning_rate=0.1, reg_alpha=0.1, reg_lambda = 0.1)
# xgbst = XGBClassifier(n_estimators=1000, learning_rate=0.1)

ltgm = lgb.LGBMClassifier( n_estimators= 500, learning_rate=0.5, random_state = 20, reg_alpha=0.01, reg_lambda = 0.5)
model= ltgm
# model= xgbst
model.fit(X, y)
# model.fit(X, y)
preds = model.predict(Xt)

prediction = pd.DataFrame(preds, columns=['pred'])
prediction.value_counts()

pred
0       3675
1        311
dtype: int64

In [390]:
# Specify the file path and name for the CSV file
csv_file_path = "output6.csv"

# Export the DataFrame to a CSV file
prediction.to_csv(csv_file_path, index=False)

In [535]:
#YOUR CODE HERE
dst3 = DecisionTreeClassifier(criterion= "gini", max_depth=16, random_state=20, min_samples_split= 10)
score(dst3, "Decision trees")


[[4539 1223]
 [1675 4253]]
Accuracy for Decision trees : 0.7521 
 f1 score:  0.7458786390740091 
 0    6214
1    5476
dtype: int64 



In [536]:
# dst3 = DecisionTreeClassifier(criterion= "gini", max_depth=17, random_state=20, min_samples_split= 10)#new_best
dst3 = DecisionTreeClassifier(criterion= "gini", max_depth=16, random_state=20, min_samples_split= 10)#new_best
# dst3 = DecisionTreeClassifier(criterion= "log_loss", max_depth=17,random_state=10) #best till
# dst3 = DecisionTreeClassifier(criterion= "log_loss", max_depth=15,random_state=10, min_samples_split = 10) #bad
# dst3 = DecisionTreeClassifier(criterion= "gini", max_depth=17,random_state=10, min_samples_split = 10)
# dst3 = DecisionTreeClassifier(criterion= "log_loss", max_depth=17,random_state=10, min_samples_split = 10) #bad
model=dst3
model.fit(X_train, y_train)
preds = model.predict(Xt)

prediction = pd.DataFrame(preds, columns=['pred'])
prediction.value_counts()

pred
0       3086
1        900
dtype: int64

In [537]:
# Specify the file path and name for the CSV file
csv_file_path = "output12.csv"

# Export the DataFrame to a CSV file
prediction.to_csv(csv_file_path, index=False)

In [538]:
# from sklearn.feature_selection import SelectKBest, chi2
# from sklearn.model_selection import GridSearchCV

# selector = SelectKBest(chi2, k=10)  # Select top 10 features
# X_train_selected = selector.fit_transform(X_train, y_train)

# # Tune hyperparameters using grid search
# param_grid = {'max_depth': [None, 5, 10, 20],
#               'min_samples_split': [2, 5, 10],
#               'min_samples_leaf': [1, 2, 4]}
# grid_search = GridSearchCV(DecisionTreeClassifier(), param_grid, cv=5)
# grid_search.fit(X_train_selected, y_train)
# best_model = grid_search.best_estimator_

# # Evaluate the model on the test set
# X_test_selected = selector.transform(X_test)
# y_pred = best_model.predict(X_test_selected)
# accuracy = accuracy_score(y_test, y_pred)
# print("Accuracy:", accuracy)